repositoryUrl: git@github.com:silver-xu/npm-module-boilerplate.git
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - '@semantic-release/git'
