language: node_js
node_js:
  - '12.14.1'
jobs:
  include:
    - stage: test
      script: yarn test
      after_success:
        - yarn codecov

    - stage: deploy
      script: semantic-release

notifications:
  email:
    recipients:
      - me@silverxu.com
    on_success: always
    on_failure: always
